org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.100

mod_id=betterfoliage
mod_name=Better Foliage Renewed
mod_license=MIT
mod_version=0.0.0-indev
mod_group_id=com.eerussianguy.betterfoliage
